// Code generated by Slice Machine. DO NOT EDIT.

import About from './About/index.svelte';
import Contacto from './Contacto/index.svelte';
import Gallery from './Gallery/index.svelte';
import Hero from './Hero/index.svelte';
import Metodos from './Metodos/index.svelte';

export const components = {
	about: About,
	contacto: Contacto,
	gallery: Gallery,
	hero: Hero,
	metodos: Metodos
};
